name: Standard Hosts Curl

on:
  workflow_dispatch:

jobs:
  curl-standard-hosts:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Standard Hosts
        run: |
          curl -s --max-time 5 -o /dev/null https://files.pythonhosted.org
          curl -s --max-time 5 -o /dev/null https://pypi.org
          curl -s --max-time 5 -o /dev/null https://results-receiver.actions.githubusercontent.com
          curl -s --max-time 5 -o /dev/null https://github.com
          curl -s --max-time 5 -o /dev/null https://api.github.com
          curl -s --max-time 5 -o /dev/null https://raw.githubusercontent.com
          curl -s --max-time 5 -o /dev/null https://codeload.github.com
          curl -s --max-time 5 -o /dev/null https://objects.githubusercontent.com
          curl -s --max-time 5 -o /dev/null https://www.w3.org
          curl -s --max-time 5 -o /dev/null https://repo.maven.apache.org
          curl -s --max-time 5 -o /dev/null https://repo.eclipse.org
          curl -s --max-time 5 -o /dev/null https://repo1.maven.org
          curl -s --max-time 5 -o /dev/null https://central.maven.org
          curl -s --max-time 5 -o /dev/null https://plugins.gradle.org
          curl -s --max-time 5 -o /dev/null https://services.gradle.org
          curl -s --max-time 5 -o /dev/null https://downloads.gradle.org
          curl -s --max-time 5 -o /dev/null https://api.osv.dev
          curl -s --max-time 5 -o /dev/null https://proxy.golang.org
          curl -s --max-time 5 -o /dev/null https://vuln.go.dev
          curl -s --max-time 5 -o /dev/null https://api.deps.dev
          curl -s --max-time 5 -o /dev/null https://dl.google.com
          curl -s --max-time 5 -o /dev/null https://osv-vulnerabilities.storage.googleapis.com
          curl -s --max-time 5 -o /dev/null https://storage.googleapis.com
          curl -s --max-time 5 -o /dev/null https://registry.npmjs.org
          curl -s --max-time 5 -o /dev/null https://sum.golang.org
          curl -s --max-time 5 -o /dev/null https://gvisor.dev
          curl -s --max-time 5 -o /dev/null https://index.rubygems.org
          curl -s --max-time 5 -o /dev/null https://rubygems.org
          curl -s --max-time 5 -o /dev/null https://nodejs.org
          curl -s --max-time 5 -o /dev/null https://api.nuget.org
          curl -s --max-time 5 -o /dev/null https://nuget.org
          curl -s --max-time 5 -o /dev/null https://dc.services.visualstudio.com
          curl -s --max-time 5 -o /dev/null https://builds.dotnet.microsoft.com
          curl -s --max-time 5 -o /dev/null https://ci.dot.net
          curl -s --max-time 5 -o /dev/null https://aka.ms
          curl -s --max-time 5 -o /dev/null https://download.visualstudio.microsoft.com
          curl -s --max-time 5 -o /dev/null https://dotnetcli.azureedge.net
          curl -s --max-time 5 -o /dev/null https://productionresultssa6.blob.core.windows.net
          curl -s --max-time 5 -o /dev/null https://productionresultssa19.blob.core.windows.net
          curl -s --max-time 5 -o /dev/null https://hosted-compute-watchdog-prod-eus-01.githubapp.com
          curl -s --max-time 5 -o /dev/null https://hosted-compute-watchdog-prod-iad-01.githubapp.com
          curl -s --max-time 5 -o /dev/null https://hosted-compute-watchdog-prod-iad-02.githubapp.com
          curl -s --max-time 5 -o /dev/null https://pipelines.actions.githubusercontent.com
          curl -s --max-time 5 -o /dev/null https://vstoken.actions.githubusercontent.com
          curl -s --max-time 5 -o /dev/null https://api.snapcraft.io
          curl -s --max-time 5 -o /dev/null https://packages.microsoft.com
          curl -s --max-time 5 -o /dev/null https://archive.ubuntu.com
          curl -s --max-time 5 -o /dev/null https://security.ubuntu.com
          curl -s --max-time 5 -o /dev/null https://deb.debian.org
          curl -s --max-time 5 -o /dev/null https://security.debian.org
          curl -s --max-time 5 -o /dev/null https://registry-1.docker.io
          curl -s --max-time 5 -o /dev/null https://auth.docker.io
          curl -s --max-time 5 -o /dev/null https://mcr.microsoft.com
          curl -s --max-time 5 -o /dev/null https://ghcr.io
          curl -s --max-time 5 -o /dev/null https://quay.io
          curl -s --max-time 5 -o /dev/null https://gcr.io
          curl -s --max-time 5 -o /dev/null https://registry.k8s.io
          curl -s --max-time 5 -o /dev/null https://cdn.jsdelivr.net
          curl -s --max-time 5 -o /dev/null https://unpkg.com
